name: "Docker Python Build"

on:
  push:
    branches:
      - main
  workflow_dispatch: # Дозволяє запускати збірку вручну кнопкою

jobs:
  docker:
    name: Build and push Python image to registry
    runs-on: ubuntu-latest

    steps:
      # 1. Завантажуємо вихідний код проєкту
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Формуємо метадані автоматично (теги та назву образу)
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=sha
            latest

      # 3. Авторизуємося в реєстрі контейнерів GitHub Container Registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 4. Збираємо Docker-образ для Python та відправляємо його в GHCR
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
